name: teams_maker
description: An app to generate team groups based on a list of members and their preferences.
publish_to: 'none'
version: 1.0.0+1

environment:
    sdk: '>=2.19.2 <3.0.0'

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    firebase_core: ^2.7.0
    cloud_firestore: ^4.4.3
    firebase_auth: ^4.2.9
    firebase_ui_auth: ^1.1.14
    firebase_storage: ^11.0.14
    firebase_crashlytics: ^3.0.15
    firebase_performance: ^0.9.0+14
    firebase_analytics: ^10.1.4
    freezed_annotation: ^2.2.0
    json_annotation: ^4.8.0
    uuid: ^3.0.7

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    build_runner: ^2.3.3
    freezed: ^2.3.2
    json_serializable: ^6.6.1

flutter:
    uses-material-design: true
