// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqjepzZC8GouMWE39coGO4culmTreGLMk',
    appId: '1:16284471065:web:6432ed2f72effdd0bbff88',
    messagingSenderId: '16284471065',
    projectId: 'teams-maker-1',
    authDomain: 'teams-maker-1.firebaseapp.com',
    storageBucket: 'teams-maker-1.appspot.com',
    measurementId: 'G-HE6PN442MN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtZuXoLE5TQqbLdLUhaB6YuvEgWVUE13c',
    appId: '1:16284471065:ios:c4d880fbfaad4a3abbff88',
    messagingSenderId: '16284471065',
    projectId: 'teams-maker-1',
    storageBucket: 'teams-maker-1.appspot.com',
    iosClientId: '16284471065-itnmvg294m7p249dutavp62ainnnk16c.apps.googleusercontent.com',
    iosBundleId: 'com.example.teamsMaker',
  );
}
